---
# Secrets & Config
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: fullstack
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: appdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: fullstack
data:
  DATABASE_URL: postgresql://admin:admin123@postgres:5432/appdb
---
# PostgreSQL StatefulSet & Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fullstack
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: fullstack
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
# Backend Deployment & Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fullstack
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sekharrapeti/fs-backend:v2   # replace with your actual image
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: db-secret

---
# Frontend Deployment & Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fullstack
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sekharrapeti/fs-frontend:v3 # replace with your repo
          ports:
            - containerPort: 80

